apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 158233516926.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: 134acb9c332a3984456ded937eab1bc7c345cbd4
- name: frontend
  newName: guestbook
  newTag: new
- name: guestbook
  newName: guestbook
  newTag: new
