apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 158233516926.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: 2784e955db644167124240e84fdfe69f409997f1
- name: frontend
  newName: 158233516926.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: b56d00e40c698f15c65e93232fab2a2f6728ef37
- name: guestbook
  newName: guestbook
  newTag: new
