apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 158233516926.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: dc92b24d7bf61952a8c1c5d2eb89d02ee2e0d428
- name: frontend
  newName: 158233516926.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: new
- name: guestbook
  newName: guestbook
  newTag: new
